name: Update Promocodes

on:
  issues:
    types: [opened, labeled]
  schedule:
    - cron: '0 */6 * * *'  # Каждые 6 часов
  workflow_dispatch:  # Ручной запуск

jobs:
  update-promocodes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update promocodes
        uses: actions/github-script@v7
        with:
          script: |
            // Тут будет скрипт для обновления промокодов
            // Можешь начать с простого - ручное добавление через Issues
